name: React Marquee Component
description: A modern, lightweight React marquee component with TypeScript support. Features customizable animations, fade effects, direction control, and accessibility-friendly scrolling text.
topics:
  - react
  - marquee
  - scroll
  - animation
  - ticker
  - carousel
  - typescript
  - component
  - ui
  - tailwind
  - css
  - modern
  - lightweight
  - accessibility
  - responsive
  - javascript
  - frontend
  - web-components
  - news-ticker
  - logo-carousel
